# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QREPORT', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rallydefects',
            old_name='name',
            new_name='defectid',
        ),
        migrations.AlterField(
            model_name='rallydefects',
            name='owner',
            field=models.CharField(max_length=200),
        ),
    ]
